//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWeb2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceWebEntities : DbContext
    {
        public ServiceWebEntities()
            : base("name=ServiceWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Monstre> Monstre { get; set; }
        public virtual DbSet<Objet> Objet { get; set; }
        public virtual DbSet<Partie> Partie { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<Salle> Salle { get; set; }
        public virtual DbSet<Texte> Texte { get; set; }
    }
}
