//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWeb2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Texte
    {
        public int Id { get; set; }
        public string type { get; set; }
        public string contenu { get; set; }

        public TexteDto toDto()
        {
            return new Mapping().toDto(this);
        }
    }
}
